project_id = "qsykyiqplslvmxdfudxq"

[functions.analyze-project-files]
verify_jwt = false

[functions.generate-media-plan]
verify_jwt = false

[functions.parse-document]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.my-work-ai-chat]
verify_jwt = false

[functions.seed-dummy-data]
verify_jwt = false
